
name: Deploy Page
on:
  push:
    branches:
    - master
    - gh-pages

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
            API_KEY: ${{ secrets.API_KEY}}
            API_KEY_ID: ${{secrets.API_KEY_ID}}
